name = "barotrauma-reactor-simulator"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-05"
workers_dev = false
route = "lbnaxx.de5.net/*"

[env.production]
account_id = "lbn20011@outlook.com"
workers_dev = false
compatibility_date = "2026-02-05"
compatibility_flags = ["nodejs_compat"]
route = "lbnaxx.de5.net/*"

[vars]
ENVIRONMENT = "production"

[assets]
directory = "./.svelte-kit/cloudflare/static"
binding = "ASSETS"

# 如果你需要绑定 KV namespaces, D1 databases, R2 buckets 等，请取消下面的注释并配置
# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"

# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id"